/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ForManager;

import Core.DataShop;
import Manager.ManagerDataShop;

/**
 *
 * @author VINH DAT
 */
public class QLDoanhSo extends javax.swing.JFrame {

    /**
     * Creates new form QKDoanhSo
     */
    public QLDoanhSo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtm = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txty = new javax.swing.JTextField();
        btnView = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtkq = new javax.swing.JTextArea();
        btnBack = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ngày");

        jLabel2.setText("Tháng");

        txtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmActionPerformed(evt);
            }
        });

        jLabel3.setText("Năm");

        btnView.setText("Xem");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        txtkq.setColumns(20);
        txtkq.setRows(5);
        jScrollPane1.setViewportView(txtkq);

        btnBack.setText("Trở về");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jButton1.setText("Hôm nay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(txtm, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txty, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jButton1)
                        .addGap(29, 29, 29)
                        .addComponent(btnView)
                        .addGap(41, 41, 41)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        ManagerDataShop aa = new ManagerDataShop();
        String d = txtd.getText().toString().trim();
        String m = txtm.getText().toString().trim();
        String y = txty.getText().toString().trim();
        if (d.equals("") && m.equals("") && y.equals("")) {
            DataShop da = aa.findAll();
            String kq = "Tổng doanh thu chưa giảm     : " + da.getDoanhthu() + "\n";
            kq += "Tổng thực thu                : " + (da.getDoanhthu() - da.getTienvoucher() - da.getGiamtichluy()) + "\n";
            kq += "Tổng số tiền dùng voucher    : " + da.getTienvoucher() + "\n";
            kq += "Tống số điểm tích lũy        : " + da.getGiamtichluy();            
            txtkq.setText(kq);
        }
        if (d.equals("") && m.equals("") && !y.equals("")) {
            int ye = Integer.parseInt(txty.getText().trim());
            DataShop da = aa.findAllByYear(ye);
            String kq = "Tổng doanh thu chưa giảm     : " + da.getDoanhthu() + "\n";
            kq += "Tổng thực thu                : " + (da.getDoanhthu() - da.getTienvoucher() - da.getGiamtichluy()) + "\n";
            kq += "Tổng số tiền dùng voucher    : " + da.getTienvoucher() + "\n";
            kq += "Tống số điểm tích lũy        : " + da.getGiamtichluy();            
            txtkq.setText(kq);
        }
        if (d.equals("") && !m.equals("") && !y.equals("")) {
            int ye = Integer.parseInt(txty.getText().toString().trim());
            int mo = Integer.parseInt(txtm.getText().toString().trim());
            DataShop da = aa.findAllByMonthYear(mo, ye);
            String kq = "Tổng doanh thu chưa giảm     : " + da.getDoanhthu() + "\n";
            kq += "Tổng thực thu                : " + (da.getDoanhthu() - da.getTienvoucher() - da.getGiamtichluy()) + "\n";
            kq += "Tổng số tiền dùng voucher    : " + da.getTienvoucher() + "\n";
            kq += "Tống số điểm tích lũy        : " + da.getGiamtichluy();            
            txtkq.setText(kq);
        }
        if (!d.equals("") && !m.equals("") && !y.equals("")) {
            int ye = Integer.parseInt(txty.getText().toString().trim());
            int mo = Integer.parseInt(txtm.getText().toString().trim());
            int da = Integer.parseInt(txtd.getText().toString().trim());
            DataShop dat = aa.findAllByDayMonthYear(da, mo, ye);
            String kq = "Tổng doanh thu chưa giảm     : " + dat.getDoanhthu() + "\n";
            kq += "Tổng thực thu                : " + (dat.getDoanhthu() - dat.getTienvoucher() - dat.getGiamtichluy()) + "\n";
            kq += "Tổng số tiền dùng voucher    : " + dat.getTienvoucher() + "\n";
            kq += "Tống số điểm tích lũy        : " + dat.getGiamtichluy();            
            txtkq.setText(kq);
        }
        aa.closeConnection();
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        Main a = new Main();
        a.setLocationRelativeTo(null);
        a.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        a.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnBackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.out.println();
        String s[] = java.time.LocalDate.now().toString().split("-");
        int a[] = new int[3];
        a[0]=Integer.parseInt(s[2]);
        a[1]=Integer.parseInt(s[1]);
        a[2]=Integer.parseInt(s[0]);
        txtd.setText(s[2]);
        txtm.setText(s[1]);
        txty.setText(s[0]);
        ManagerDataShop aa = new ManagerDataShop();
        DataShop dat = aa.findAllByDayMonthYear(a[0], a[1], a[2]);
        aa.closeConnection();
        String kq = "Tổng doanh thu chưa giảm     : " + dat.getDoanhthu() + "\n";
        kq += "Tổng thực thu                : " + (dat.getDoanhthu() - dat.getTienvoucher() - dat.getGiamtichluy()) + "\n";
        kq += "Tổng số tiền dùng voucher    : " + dat.getTienvoucher() + "\n";
        kq += "Tống số điểm tích lũy        : " + dat.getGiamtichluy();            
        txtkq.setText(kq);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLDoanhSo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLDoanhSo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLDoanhSo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLDoanhSo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLDoanhSo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnView;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtd;
    private javax.swing.JTextArea txtkq;
    private javax.swing.JTextField txtm;
    private javax.swing.JTextField txty;
    // End of variables declaration//GEN-END:variables
}
